comment: false
coverage:
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
