version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./config
        target: /var/www/html/config
      - type: bind
        source: ./storage
        target: /var/www/html/storage
      - type: bind
        source: ./userfiles/media
        target: /var/www/html/userfiles/media
selenium:
  image: 'selenium/standalone-chrome'
  volumes:
    - '/dev/shm:/dev/shm'
  networks:
    - sail
depends_on:
  - mysql
  - redis
  - selenium
volumes:
  storage:
  config:
  media:
