version: '3'
services:
  php-apache:
    container_name: website-frontend
    image: mitlabs/apache-php7.4
    ports:
      - 80:80
    volumes:
     - ./:/var/www/html
    links:
      - 'mariadb'
  mariadb:
    image: mariadb:10.3
    volumes:
    - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'laravel'
      MYSQL_DATABASE: 'laravel'
    ports:
      - 3306:3306
volumes:
  mariadb:
