version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - type: bind
        source: ./config
        target: /var/www/html/config
      - type: bind
        source: ./storage
        target: /var/www/html/storage
      - type: bind
        source: ./userfiles/media
        target: /var/www/html/userfiles/media

volumes:
  storage:
  config:
  media: