name: Dusk
on: [push,pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-versions: ['7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, sqlite, xml,
        coverage: xdebug #optional
    - name: zstd act workaround
      run: sudo apt install zstd
    - name: google-chrome install
      run: |
        sleep 3
        sudo apt-get install libxss1 libappindicator1 libindicator7
        sleep 3
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        sudo dpkg -i google-chrome*.deb
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Use composer.json for key, if composer.lock is not committed.
        # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Install Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Dusk updater install
      run: |
        composer require --dev staudenmeir/dusk-updater:"^1.1"
        php artisan package:discover --ansi
    - name: Dusk update
      run: php artisan dusk:update
    - name: Start Chrome Driver
      run: |
        vendor/laravel/dusk/bin/chromedriver-linux --version
        vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Run Dusk Tests
      run: |
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan dusk
