name: Dusk Apache
on: [push,pull_request]

jobs:
  dusk_apache:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        php-versions: ['7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: true
        envkey_APP_ENV: "testing"
        file_name:
          .env
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, fileinfo, mysql, gd, curl, zip, sqlite, xml,
        coverage: xdebug #optional
    - name: zstd act workaround
      run: sudo apt install zstd
    - name: google-chrome install
      run: |
        sleep 3
        sudo apt-get install libxss1 libappindicator1 libindicator7 libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4
        sudo apt-get install xvfb gtk2-engines-pixbuf
        sudo apt-get install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
        sleep 3
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        sudo dpkg -i google-chrome*.deb
        sudo apt-get install -y libnss3 chromium-browser
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        # Use composer.json for key, if composer.lock is not committed.
        # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    - name: Install Chrome Driver
      run: php artisan dusk:install
    - name: Dusk updater install
      run: |
        composer require --dev staudenmeir/dusk-updater:"^1.1"
        php artisan package:discover --ansi
    - name: Dusk update
      run: php artisan dusk:update
    - name: Start Chrome Driver
      run: |
        vendor/laravel/dusk/bin/chromedriver-linux --version
        vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Setup Apache
      uses: thunder/apache-shiva-php-action@v1
      with:
        php-version: '7.4'
        site-directory: /home/runner/work/microweber/microweber/
        # Defaults to 8888
        http-port: 8000
    - name: Run Dusk Tests
      run: |
        APP_ENV=testing
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan dusk --testsuite MicroweberCoreTests
    - name: Run Dusk Shop Tests
      run: |
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan dusk --testsuite MicroweberShopTests
    - name: Run Dusk Multilanguage Tests
      run: |
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan dusk --testsuite MicroweberMultilanguageTests
    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: tests/Browser/screenshots
    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: console
        path: tests/Browser/console
    - name: Upload Laravel Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: storage-logs
        path: storage/logs
