name: Dusk
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  test_schedule:
    name: Check schedule
    runs-on: ubuntu-latest
    steps:
      - name: Create cache file
        run: |
          mkdir check-SHA
          echo ${{ github.sha }} > github-sha.txt

      - name: Check SHA
        id: check_sha
        uses: actions/cache@v1
        with:
          path: check-SHA
          key: check-SHA-${{ github.sha }}

      - name: Some subsequent steps
        if: steps.check_sha.outputs.cache-hit != 'true'
        run: echo "Execute the subsequent steps"
  dusk:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        php-versions: [ '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEBUG: true
          APP_ENV: "testing"
      - uses: ./.github/actions/setup-php
        with:
          php_version: ${{ matrix.php-versions }}
      - name: Run Laravel Server
        #run: php artisan serve-test --env=testing > /dev/null 2>&1 &
        #run: APP_ENV=testing && php -d variables_order=EGPCS -S 127.0.0.1:8000 > /dev/null 2>&1 &
        run: APP_ENV=testing && php -d variables_order=EGPCS -S 127.0.0.1:8000 > /home/runner/work/microweber/microweber/storage/logs/serve.log 2>&1 &
      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk --testsuite MicroweberCoreTests
      - name: Run Dusk Shop Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk --testsuite MicroweberShopTests
      - name: Run Dusk Multilanguage Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk --testsuite MicroweberMultilanguageTests
      - name: Run Dusk Template Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk --testsuite MicroweberTemplatesTests
      - name: Run Dusk Slow Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan dusk --testsuite MicroweberSlowTests
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
      - name: Upload Laravel Storage
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: storage
          path: storage
      - name: Upload Laravel config
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: config
          path: config
