on:
  workflow_run:
    workflows: ["MicroweberBuildAndUpload"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test

         
